### ISSUE TITLE
issue with Alpha versions

### ISSUE THREAD

**Issue by smachefert** [Daniel-KM/UpgradeToOmekaS#17]
@Daniel-KM there is an issue with this list, as of writing, Mapping module has its version set to 2.0.0-alpha1 in omeka_s_modules_versions.tsv . The issue is that if I use [Omeka-S-module-OaiPmhRepository](https://github.com/Daniel-KM/Omeka-S-module-OaiPmhRepository) which includes Generic module to check for updates, the list of modules displays a message indicating that Mapping module should be updated, even if I am at the latest stable version available.

I have spent some time trying to figure out why I had a message telling me to update when clicking on the module name was sending me to a page where the release available was exactly the one I had on my install. This is because of the 2 alpha version in the file.

I don't know what the best way of fixing this is, either fixing the version number in this list, or removing the dependency in OaiPmhRepository if it's not useful anymore.

**Comment by Daniel-KM** [comment]
Je pense que je l'ai corrigé dans la dernière version de Common, mais il faudrait tester.

**Comment by smachefert** [comment]
Merci @Daniel-KM je suis un peu en retard sur les mises à jour et je vais attendre un peu pour me faire une session de mise à jour complète donc je ne vais pas tester tout de suite mais je te fais confiance
